version: '3'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./esdata_:/usr/share/elasticsearch/data
    
    # networks:
    #   - elastic

#   kib8:
#     image: docker.elastic.co/kibana/kibana:8.9.1
#     container_name: kib8
#     environment:
#       - node.name=kib8
#       - cluster.name=es-docker-cluster
#       - ELASTICSEARCH_HOSTS=http://es8:9200
#       - ELASTICSEARCH_USERNAME=elastic
#       - ELASTICSEARCH_PASSWORD=trongnt123
#     ports:
#       - "9000:5601"
#     networks:
#       - elastic

#     depends_on:
#       - es8
# volumes:
#   data:
#     driver: local
# networks:
#   elastic:
#     driver: bridge


